name: ISSUE INFO 


on: 
  issues:
    types: [opened, edited]

jobs:
  issue-info:
    runs-on: ubuntu-latest
    
    steps:
      - name: Display issue information
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
         printf 'Issue #%s - %s\n' "$ISSUE_NUMBER" "$ISSUE_TITLE"
